name: Deploy maven artifacts

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      artifact-id:
        required: true
        type: string
      version-number:
        required: true
        type: string
      project-version:
        required: true
        type: string
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true

jobs:
  run:
    name: Deploy maven artifacts
    runs-on: ubuntu-latest

    steps:
#      - name: Select Nexus repository
#        run: |
#          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
#            echo "NEXUS_REPOSITORY=maven-releases" >> "$GITHUB_ENV"
#          else
#            echo "NEXUS_REPOSITORY=maven-snapshots" >> "$GITHUB_ENV"
#          fi
#          echo "NEXUS_URL=repository.folio.org" >> "$GITHUB_ENV"

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Java for Nexus
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version}}
          distribution: 'temurin'
          server-id: folio-nexus
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Deploy to Nexus
        run: mvn --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.nexus-username }}
          MAVEN_PASSWORD: ${{ secrets.nexus-password }}


#      - name: Do build package
#        run: mvn clean package -DskipTests
#
#      - name: Show contents of target directory
#        run: ls target

      # - name: Upload artifact to Primary Nexus Repo
      #   uses: SourceSpring/action-nexus-upload@v0.1.13
      #   with:
      #     nexus-repo-url: ${{ env.NEXUS_URL }}
      #     nexus-username: ${{ secrets.GHA_NEXUS_USERNAME }}
      #     nexus-password: ${{ secrets.GHA_NEXUS_PASSWORD }}
      #     nexus-repository: ${{ env.NEXUS_REPOSITORY }}
      #     artifact-path: "target/${{ inputs.artifact-id }}-${{ inputs.project-version }}.jar"
      #     artifact-format: "maven"
      #     artifact-group-id: "org.folio"
      #     artifact-id: ${{ inputs.artifact-id }}
      #     artifact-version: ${{ inputs.version-number }}  # TODO: ? Should this be: ${{ inputs.project-version }}

#      - name: "Upload test file to Nexus"
#        id: nexus-upload
#        # ToDo: change/update the line below when testing is completed
#        uses: ModeSevenIndustrialSolutions/nexus-upload-action@v0.1.8
#        with:
#          nexus_server: ${{ env.NEXUS_URL }}
#          nexus_username: ${{ secrets.GHA_NEXUS_USERNAME }}
#          nexus_password: ${{ secrets.GHA_NEXUS_PASSWORD }}
#          nexus_repository: "maven-folio"
#          upload_directory: target
#          filename_suffix: .jar
#
#      - name: "Report results"
#        run: |
#          # Report results
#          echo "errors: ${{ steps.nexus-upload.outputs.errors }}"
#          echo "successes: ${{ steps.nexus-upload.outputs.successes }}"
#          echo "failures: ${{ steps.nexus-upload.outputs.failures }}"
