name: Deploy maven artifacts

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      version-number:
        required: true
        type: string
      project-version:
        required: true
        type: string

jobs:
  run:
    name: Deploy maven artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Select Nexus repository
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "NEXUS_REPOSITORY=maven-releases" >> "$GITHUB_ENV"
          else
            echo "NEXUS_REPOSITORY=maven-snapshots" >> "$GITHUB_ENV"
          fi
          echo "NEXUS_URL=https://repository.folio.org" >> "$GITHUB_ENV"

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version}}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Do build package
        run: mvn clean package -DskipTests

      - name: Show contents of target directory
        run: ls target
      
      - name: Get artifactId
        id: artifact
        run: |
          echo "artifact-id=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: Upload artifact to Primary Nexus Repo
        uses: SourceSpring/action-nexus-upload@v0.1.13
        with:
          nexus-repo-url: ${{ env.NEXUS_URL }}
          nexus-username: ${{ secrets.GHA_NEXUS_USERNAME }}
          nexus-password: ${{ secrets.GHA_NEXUS_PASSWORD }}
          nexus-repository: ${{ env.NEXUS_REPOSITORY }}
          artifact-path: "target/${{ steps.artifact.outputs.artifact-id }}-${{ inputs.project-version }}.jar"
          artifact-format: "maven2"
          artifact-group-id: "org.folio"
          artifact-id: ${{ steps.artifact.outputs.artifact-id }}
          artifact-version: ${{ inputs.version-number }}

      - name: Upload artifact to maven-folio Nexus Repo always
        uses: SourceSpring/action-nexus-upload@v0.1.13
        with:
          nexus-repo-url: ${{ env.NEXUS_URL }}
          nexus-username: ${{ secrets.GHA_NEXUS_USERNAME }}
          nexus-password: ${{ secrets.GHA_NEXUS_PASSWORD }}
          nexus-repository: "maven-folio"
          artifact-path: "target/${{ steps.artifact.outputs.artifact-id }}-${{ inputs.project-version }}.jar"
          artifact-format: "maven2"
          artifact-group-id: "org.folio"
          artifact-id: ${{ steps.artifact.outputs.artifact-id }}
          artifact-version: ${{ inputs.version-number }}
