name: Maven upload build-time apidocs

# If maven generated apidocs during its build then do special upload to S3.

on:
  workflow_call:
#    secrets:
# Add the S3 secrets

jobs:
  run:
    name: Upload build-time apidocs
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact apidocs
        uses: actions/download-artifact@v7
        with:
          name: apidocs
          path: apidocs

      - name: Prepare upload apidocs directory
        run: |
          uploadBaseDir="upload/${GITHUB_REPOSITORY##*/}"
          uploadDir="${uploadBaseDir}/u"
          mkdir -p ${uploadDir}
          find ./apidocs/*.* | sed 's|^.*/||' > ${uploadDir}/files-upload.txt
          cp apidocs/*.* ${uploadDir}
          cat ${uploadDir}/files-upload.txt

      - name: Do ls
        run: ls -R ${uploadDir}
