name: Maven upload build-time apidocs

# If maven generated apidocs during its build then do special upload to S3.

env:
  AWS_S3_BUCKET: 'foliodocs'
  AWS_S3_FOLDER: 'api'
  AWS_S3_REGION: 'us-east-1'

on:
  workflow_call:
    secrets:
      AWS_S3_ACCESS_KEY_ID:
        required: true
      AWS_S3_ACCESS_KEY:
        required: true

jobs:
  run:
    name: Upload build-time apidocs
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact apidocs
        uses: actions/download-artifact@v7
        with:
          name: apidocs
          path: apidocs

      - name: Prepare upload apidocs directory
        run: |
          uploadBaseDir="upload/${GITHUB_REPOSITORY##*/}"
          uploadDir="${uploadBaseDir}/u"
          mkdir -p ${uploadDir}
          find ./apidocs/*.* | sed 's|^.*/||' > ${uploadDir}/files-upload.txt
          cp apidocs/*.* ${uploadDir}
          cat ${uploadDir}/files-upload.txt

      - name: Publish to AWS S3
        uses: sai-sharan/aws-s3-sync-action@v0.1.0
        with:
          access_key: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_S3_ACCESS_KEY }}
          region: ${{ env.AWS_S3_REGION }}
          source: upload
          destination_bucket: ${{ env.AWS_S3_BUCKET }}
          destination_prefix: ${{ env.AWS_S3_FOLDER }}
          delete: false
          quiet: false
